### ISSUE TITLE
Is there support for Electron 10+?

### ISSUE THREAD

**Issue by PaulRyan97** [sibnerian/electron-promise-ipc#33]
I tried updating my application from electron 7 to 10 and I found some weird behaviour with this module. It looks like in some cases the renderer does not receive events from the main process. I can't find a reason for this having gone through the source code and the various electron changelogs. Some of my calls still work even though they're identical to others that do.

I dropped back to electron 9.3 and that does work so there must be some breaking change occurring there.

**Comment by nanajellyvision** [comment]
Bumping this since I'm also trying to get this to work on electron v11. I'm getting this error:

`TypeError: Cannot read property 'once' of undefined
    at /repo/node_modules/electron-promise-ipc/build/base.js:35:32
    at new Promise (<anonymous>)
    at PromiseIpcMain.PromiseIpcBase.send (/repo/node_modules/electron-promise-ipc/build/base.js:31:16)
    at PromiseIpcMain.send (/repo/node_modules/electron-promise-ipc/build/mainProcess.js:39:38)`

**Comment by sibnerian** [comment]
Thanks for bumping this! What would be helpful is a [minimum reproduction](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) - the simplest possible Electron app that demonstrates the failure. I assume the issue is with a `once` call somewhere from the stack trace, but without a minimal repro I can't debug very easily.

**Comment by sibnerian** [comment]
FWIW I've had no issues in my tester app with Electron 11.0.3.
